- .env.test
- composer.json
- composer.lock
- config/bundles.php
- config/packages/acseo_typesense.yaml
- config/packages/liip_imagine.yaml
- config/packages/sensio_framework_extra.yaml
- config/packages/twig_component.yaml
- config/services.yaml
- phpunit.xml.dist
- src/Twig/Components/AddBookToShelf.php
- src/Twig/Components/AddNewShelf.php
- src/Twig/Components/BootstrapModal.php
- src/Twig/Components/FieldGuesser.php
- src/Twig/Components/InlineEditBook.php
- src/Twig/Components/InlineEditGroup.php
- src/Twig/Components/InlineEditInteraction.php
- src/Twig/Components/InlineEditMultiple.php
- src/Twig/Components/Search.php
- src/Twig/Components/UploadBookPicture.php
- src/Twig/FilteredBookUrl.php
- symfony.lock
- tests/GedmoTest.php
- tests/SampleTest.php
Remove deprecation and upgrade vendors
> Remove deprecations and start testing

- assets/ReadEbook.vue
- assets/read-ebook.js
- assets/styles/global.scss
- docker-compose.yml
- package-lock.json
- package.json
- src/Controller/BookController.php
- src/Service/BookFileSystemManager.php
- src/Service/ThemeSelector.php
- src/Twig/Components/InlineEditBook.php
- src/Twig/Runtime/ThemeExtensionRuntime.php
- templates/bare.html.twig
- templates/book/index.html.twig
- templates/book/reader-files-epub.html.twig
- templates/components/InlineEditBook.html.twig
- templates/themes/dark/bare.html.twig
- webpack.config.js
* Support for reading epub online (not tested with mobi)
* Show Book UUID in Ux
* Use Vue.js and <https://github.com/jinhuan138/vue-book-reader/> (based on foliate-js)
> Ebook Online reading

- assets/app.js
- composer.json
- src/Controller/BookController.php
- src/EventListener/LanguageListener.php
- src/EventListener/LoginListener.php
- templates/base.html.twig
- templates/book/index.html.twig
Added error handling in the book relocation process to provide user feedback on success or failure. Migrated flash messages from alerts to Bootstrap toasts for enhanced user experience. Updated PHP requirement to 8.2 in composer.json.
> Implement error handling and toast notifications for relocation

- Dockerfile
Fix https://github.com/biblioverse/biblioteca-docker/issues/13
> Fix build for v2.0.1

- src/Ai/Context/ContextBuilder.php
- src/Ai/Context/EpubContextBuilder.php
- src/Command/BooksAiCommand.php
Added exception handling in context and EPUB builders to prevent crashes and log errors via `OutputInterface`. Enhanced `BooksAiCommand` with an `overwrite` option, better progress tracking, and conditional checks for generating summaries and tags.
> Error handling and output improvements in AI Tagging.

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/tests.yml
> Fix coverage comparison

- doc/src/content/docs/installing/1-helm.mdx
- doc/src/content/docs/installing/1-initial-setup.mdx
- doc/src/files/helm-values.yml
This PR adds an entry to the documentation for the newly created Helm Chart
> Add instructions to install with Helm

- renovate.json
> Fine tune renovate configuration

- renovate.json
> renovate: Only update lockfile for composer updates

- composer.json
- composer.lock
- tests/Ai/AiModelControllerTest.php
- tests/Command/CreateUserCommandTest.php
> Update symfony packages

- doc/src/content/docs/guides/Administrator/ai-features-configuration.mdx
doc: Add example values for openAI
> doc: Add example values for openAI

- .env
- doc/src/content/docs/installing/1-initial-setup.mdx
- doc/src/content/docs/installing/dotenv-config.md
* Remove unused env values from doc
* Change doc to use a `.env.local` file
> Doc update

- config/services.yaml
- doc/src/content/docs/guides/Administrator/ai-features-configuration.mdx
- src/Ai/Context/AmazonContextBuilder.php
- src/Ai/Context/ContextBuilder.php
- src/Ai/Context/ContextBuildingInteface.php
- src/Ai/Context/ContextBuildingInterface.php
- src/Ai/Context/EpubContextBuilder.php
- src/Ai/Context/SummaryContextBuilder.php
- src/Ai/Context/WikipediaContextBuilder.php
- src/Ai/Prompt/AbstractBookPrompt.php
- src/Ai/Prompt/PromptFactory.php
- src/Twig/Components/InlineEditBook.php
- templates/book/index.html.twig
- templates/components/InlineEditBook.html.twig
- templates/components/UploadBookPicture.html.twig
- translations/messages+intl-icu.en.yaml
- translations/messages+intl-icu.fr.yaml
- Inject language into IA prompt
- Add missing translations
- Book.language is editable
- Fix typo in interface name 
(deprecate `App\Ai\Context\ContextBuildingInteface.php` -> `ContextBuildingInterface.php`)
> feat(language): Better language support

- doc/src/content/docs/installing/2-new-versions.mdx
- upgrade.sh
I am using a script to update the app on my server. I think it could be comited.
> Upgrade script

- composer.json
- composer.lock
chore(deps): Upgrade typesense bundle to support enum
> chore(deps): Upgrade typesense bundle to support enum

- src/Ai/Prompt/SearchHintPrompt.php
- src/Ai/Prompt/SummaryPrompt.php
- src/Ai/Prompt/TagPrompt.php
- src/Config/ConfigValue.php
- src/Controller/AiModelController.php
- src/Form/AiConfigurationType.php
- translations/messages+intl-icu.en.yaml
- translations/messages+intl-icu.fr.yaml
> Refine AI prompt parsing and model configuration handling

- composer.json
- migrations/Version20250202150749.php
- src/Entity/BookInteraction.php
- Update annotation to fix deprecation
- Add the missing migration change
> fix(migration): Add missing migration

- composer.json
- composer.lock
- upgrade.sh
Populate will check readiness of typesense & database before processing it.
> chore(dependency): Upgrade typsense bundle to have automatic wait

- assets/styles/global.scss
- config/packages/biblioverse_typesense.yaml
- src/Controller/AuthorController.php
- src/Controller/SerieController.php
- templates/author/detail.html.twig
- templates/book/_book-row-empty.html.twig
- templates/book/_book-row.html.twig
- templates/book/_empty.html.twig
- templates/book/_teaser.html.twig
- templates/book/index.html.twig
- templates/components/Search.html.twig
- templates/components/_rating.html.twig
- templates/serie/detail.html.twig
This PR brings some UI Improvements
- Add "Publisher" and "Age category" links in the right block of those pages
- Fix progress bar calculation
- Fix vertical alignment of icons in the hero bar
- Fix vertical alignement of the title
- Change rating's color in book rows to match the rest
- Index publisher field (search links point to it but the field didn't exist)
> Various improvements

- assets/styles/components/hero.css
- templates/author/detail.html.twig
- templates/book/_cover.html.twig
- templates/book/index.html.twig
- templates/serie/detail.html.twig
Small friday night PR:
This uses the same image as the cover so it doesn't increase the weight of the page.
> hero background images

- assets/styles/components/bookWithDetails.css
- assets/styles/components/card.css
- assets/styles/components/hero.css
- assets/styles/components/heroProgress.css
- assets/styles/components/infoBlock.css
- assets/styles/components/menuBlock.css
- assets/styles/components/table.css
- assets/styles/global.scss
- assets/styles/layout.css
- assets/styles/variables.css
- src/Menu/MenuBuilder.php
- templates/author/detail.html.twig
- templates/base.html.twig
- templates/book/_book-row.html.twig
- templates/main_menu.html.twig
- templates/serie/detail.html.twig
> Improved left menu, branding colors

- config/packages/biblioverse_typesense.yaml
- src/Entity/Book.php
> Index tags/summary empty status

- src/Entity/Book.php
> Use addTags and AddAuthors methods

- src/Ai/Communicator/GeminiCommunicator.php
- src/Ai/Communicator/PerplexicaCommunicator.php
- src/Ai/Prompt/AbstractBookPrompt.php
- src/Ai/Prompt/SummaryPrompt.php
- src/Controller/AiModelController.php
- src/Entity/Book.php
- src/Twig/Components/Assistant.php
- templates/ai_model/show.html.twig
> Perplexica110

- assets/styles/components/assistant.css
- assets/styles/global.scss
- config/packages/biblioverse_typesense.yaml
- src/Ai/Prompt/SummaryPrompt.php
- src/Controller/BookController.php
- src/Controller/DefaultController.php
- templates/ai_model/_form.html.twig
- templates/ai_model/edit.html.twig
- templates/ai_model/index.html.twig
- templates/ai_model/new.html.twig
- templates/book/consume.html.twig
- templates/book/upload.html.twig
- templates/components/Assistant.html.twig
- templates/components/BootstrapModal.html.twig
- templates/default/notverified.html.twig
- templates/instance_configuration/_form.html.twig
- templates/instance_configuration/edit.html.twig
- templates/instance_configuration/index.html.twig
- templates/user/_form.html.twig
- templates/user/profile.html.twig
- tests/Controller/Opds/OpdsAccessControllerTest.php
- translations/messages+intl-icu.en.yaml
- translations/messages+intl-icu.fr.yaml
This PR introduces many small Quality of life improvements:
- fix a typo in the assistant prompt markdwon -> markdown
- index the book_path field: useful when verifying a lot of books that were previously manually ordered
- fix missing labels on book upload form
- on the "not verified" view, sort by "bookPath" to verify folder by folder (useful as I currently have thousands of books to verify, the current ordering of "serieIndex" makes it quite confusing to make progress on the verification)
- update forms in many places of the admin to use the design's "cards" look (screenshot below)
- replace static text here and there with translated text
- add icons here and there
- Edit Assistant
- Make middle column scrollable independently from the chat
- move the AI button on top of fields
- make …
> A whole lot of small improvements

- assets/login.js
- assets/styles/components/login.css
- assets/styles/global.scss
- package-lock.json
- package.json
- templates/login/login.html.twig
- webpack.config.js
This PR brings a new animated login screen
Small video: https://github.com/user-attachments/assets/8bd574d2-e605-42d8-b80d-3a5610e932eb
This login page is made using the following:
- Create 10 columns using flex, each column is animated separately (each start in a different direction)
- Fill each column with 8 to 12 images
- Images are from popular comic books (Then compressed using https://blurha.sh/) so there are no privacy concern with leaking comic books from people's libraries
- The whole container is skewed using a CSS `transform` for a nice visual effect
- An overlay with a blur is added on top for a nicer visual effect
- Using requestAnimationFrame to animate efficiently.
I checked in Chrome Web tool's performance tab; the animation is super smooth so that shouldn't be a …
> New login page

- templates/author/detail.html.twig
- templates/book/_cover.html.twig
- templates/book/index.html.twig
- templates/serie/detail.html.twig
In some cases the progress bar breaks because of a division by zero, let's make sure this doesn't break too much :)
> Fix more division by Zero

- .env
> bug(search): use existing model

- migrations/Version20250404084822.php
- src/Command/BooksAiCommand.php
- src/Controller/SuggestionController.php
- src/Entity/Book.php
- src/Entity/Suggestion.php
- src/Menu/MenuBuilder.php
- src/Repository/SuggestionRepository.php
- templates/main_menu.html.twig
- templates/suggestion/index.html.twig
- translations/messages+intl-icu.en.yaml
- translations/messages+intl-icu.fr.yaml
> Do not accept automatically from command but propose suggestions

- src/Controller/DefaultController.php
- src/Controller/SuggestionController.php
- src/Repository/BookRepository.php
- templates/default/dashboard.html.twig
- templates/suggestion/index.html.twig
> feature(performance): improve displays

- config/services.yaml
- doc/src/content/docs/installing/dotenv-config.md
- src/Controller/BookController.php
- src/Kobo/DownloadHelper.php
- src/Service/EpubMetadataService.php
- templates/book/index.html.twig
- tests/Service/EpubMetadataServiceTest.php
Introduced `EpubMetadataService` to dynamically embed metadata into EPUB files during download. Updated controllers and download logic to support this feature. Added comprehensive unit tests to ensure functionality and error handling.
Explain your PR here
> feat(download): embed EPUB metadata on download
